server.port: 8080

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@localhost:27017/review-service?authSource=admin}
      auto-index-creation: true

application:
  security:
    allowed-origin: ${ALLOWED_ORIGIN:*}
    public-signature-key: ${PUBLIC_SIGNATURE_KEY:public-key}
    private-signature-key: ${SIGNING_SIGNATURE_KEY:secret-signing-key}
